# Generated by Django 5.0.2 on 2024-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('a', 'accepted'), ('r', 'rejected')], default='w', max_length=20),
        ),
    ]
